version: '3'
services:
  proxy:
    build:
      context: .
    ports:
      - "80:80"
    volumes:
      - "./app/:/var/www/html/"
  api:
    restart: always
    build:
      context: .
      dockerfile: Server.Dockerfile
    command: npx nodemon index.js
    volumes:
      - "./artifacts/:/app/artifacts/"

  database:
    image: postgres
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: timonapath
