module.exports.Docs = require('./docs')
module.exports.Snippets = require('./snippets')
module.exports.Articles = require('./articles')
module.exports.Replies = require('./replies')
module.exports.Vocabulary = require('./vocabulary')